import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";


const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  variable: "--font-titillium-web",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Globetrotter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWeb.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
